module WOW::Definitions
  build 19033 do
    namespace :db do
      table :achievement do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :faction,                     type: :int32,   tc_value: ''
        e   2,    :instance_id,                 type: :int32,   tc_value: ''
        e   3,    :supercedes,                  type: :uint32,  tc_value: ''
        e   4,    :title,                       type: :string,  tc_value: ''
        e   5,    :description,                 type: :string,  tc_value: ''
        e   6,    :category,                    type: :uint32,  tc_value: ''
        e   7,    :points,                      type: :uint32,  tc_value: ''
        e   8,    :ui_order,                    type: :uint32,  tc_value: ''
        e   9,    :flags,                       type: :uint32,  tc_value: ''
        e   10,   :icon_id,                     type: :uint32,  tc_value: ''
        e   11,   :reward,                      type: :string,  tc_value: ''
        e   12,   :minimum_criteria,            type: :uint32,  tc_value: ''
        e   13,   :shares_criteria,             type: :uint32,  tc_value: ''
        e   14,   :criteria_tree,               type: :uint32,  tc_value: ''
      end

      table :area_table do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :map_id,                      type: :uint32,  tc_value: ''
        e   2,    :parent_area_id,              type: :uint32,  tc_value: ''
        e   3,    :area_bit,                    type: :uint32,  tc_value: ''
        e   4,    :flags_1,                     type: :uint32,  tc_value: ''
        e   5,    :flags_2,                     type: :uint32,  tc_value: ''
        e   6,    :sound_provider_pref,         type: :uint32,  tc_value: ''
        e   7,    :sound_provider_pref_underwater, type: :uint32, tc_value: ''
        e   8,    :ambience_id,                 type: :uint32,  tc_value: ''
        e   9,    :zone_music,                  type: :uint32,  tc_value: ''
        e   10,   :zone_name,                   type: :string,  tc_value: ''
        e   11,   :intro_sound,                 type: :uint32,  tc_value: ''
        e   12,   :exploration_level,           type: :uint32,  tc_value: ''
        e   13,   :area_name,                   type: :string,  tc_value: ''
        e   14,   :faction_group_mask,          type: :uint32,  tc_value: ''
        e   15,   :liquid_type_1_id,            type: :uint32,  tc_value: ''
        e   16,   :liquid_type_2_id,            type: :uint32,  tc_value: ''
        e   17,   :liquid_type_3_id,            type: :uint32,  tc_value: ''
        e   18,   :liquid_type_4_id,            type: :uint32,  tc_value: ''
        e   19,   :ambient_multiplier,          type: :float,   tc_value: ''
        e   20,   :mount_flags,                 type: :uint32,  tc_value: ''
        e   21,   :uw_intro_music,              type: :uint32,  tc_value: ''
        e   22,   :uw_zone_music,               type: :uint32,  tc_value: ''
        e   23,   :uw_ambience,                 type: :uint32,  tc_value: ''
        e   24,   :world_pvp_id,                type: :uint32,  tc_value: ''
        e   25,   :pvp_combat_world_state_id,   type: :int32,   tc_value: ''
        e   26,   :wild_battle_pet_level_min,   type: :uint32,  tc_value: ''
        e   27,   :wild_battle_pet_level_max,   type: :uint32,  tc_value: ''
        e   28,   :wind_settings_id,            type: :uint32,  tc_value: ''
      end

      table :char_titles do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :condition_id,                type: :uint32,  tc_value: ''
        e   2,    :name,                        type: :string,  tc_value: ''
        e   3,    :name_1,                      type: :string,  tc_value: ''
        e   4,    :mask_id,                     type: :uint32,  tc_value: ''
        e   5,    :flags,                       type: :uint32,  tc_value: ''
      end

      table :creature do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :creature_type_id,            type: :uint32,  tc_value: ''
        e   2,    :unk_1,                       type: :uint32,  tc_value: ''
        e   3,    :unk_2,                       type: :uint32,  tc_value: ''
        e   4,    :unk_3,                       type: :uint32,  tc_value: ''
        e   5,    :unk_4,                       type: :uint32,  tc_value: ''
        e   6,    :unk_5,                       type: :uint32,  tc_value: ''
        e   7,    :unk_6,                       type: :uint32,  tc_value: ''
        e   8,    :unk_7,                       type: :uint32,  tc_value: ''
        e   9,    :unk_8,                       type: :uint32,  tc_value: ''
        e   10,   :unk_9,                       type: :uint32,  tc_value: ''
        e   11,   :unk_10,                      type: :uint32,  tc_value: ''
        e   12,   :unk_11,                      type: :uint32,  tc_value: ''
        e   13,   :unk_12,                      type: :uint32,  tc_value: ''
        e   14,   :name,                        type: :string,  tc_value: ''
        e   15,   :unk_13,                      type: :uint32,  tc_value: ''
        e   16,   :unk_14,                      type: :uint32,  tc_value: ''
        e   17,   :unk_15,                      type: :uint32,  tc_value: ''
        e   18,   :unk_16,                      type: :uint32,  tc_value: ''
        e   19,   :unk_17,                      type: :uint32,  tc_value: ''
      end

      table :creature_difficulty do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :creature_id,                 type: :uint32,  tc_value: ''
        e   2,    :faction_id,                  type: :uint32,  tc_value: ''
        e   3,    :expansion,                   type: :uint32,  tc_value: ''
        e   4,    :minimum_level,               type: :uint32,  tc_value: ''
        e   5,    :maximum_level,               type: :uint32,  tc_value: ''
        e   6,    :flags_1,                     type: :uint32,  tc_value: ''
        e   7,    :flags_2,                     type: :uint32,  tc_value: ''
        e   8,    :flags_3,                     type: :uint32,  tc_value: ''
        e   9,    :flags_4,                     type: :uint32,  tc_value: ''
        e   10,   :flags_5,                     type: :uint32,  tc_value: ''
      end

      table :creature_display_info do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :creature_model_id,           type: :uint32,  tc_value: ''
        e   2,    :creature_sound_id,           type: :uint32,  tc_value: ''
        e   3,    :creature_display_extra_id,   type: :uint32,  tc_value: ''
        e   4,    :creature_model_scale,        type: :float,   tc_value: ''
        e   5,    :unk_1,                       type: :float,   tc_value: ''
        e   6,    :creature_model_alpha,        type: :uint32,  tc_value: ''
        e   7,    :texture_variation_1_name,    type: :string,  tc_value: ''
        e   8,    :texture_variation_2_name,    type: :string,  tc_value: ''
        e   9,    :texture_variation_3_name,    type: :string,  tc_value: ''
        e   10,   :portrait_texture_name,       type: :string,  tc_value: ''
        e   11,   :size_class,                  type: :uint32,  tc_value: ''
        e   12,   :blood,                       type: :int32,   tc_value: ''
        e   13,   :npc_sound_id,                type: :uint32,  tc_value: ''
        e   14,   :particle_color_id,           type: :uint32,  tc_value: ''
        e   15,   :creature_geoset_data,        type: :uint32,  tc_value: ''
        e   16,   :object_effect_package_id,    type: :uint32,  tc_value: ''
        e   17,   :anim_replacement_set_id,     type: :uint32,  tc_value: ''
        e   18,   :flags,                       type: :uint32,  tc_value: ''
        e   19,   :gender,                      type: :int32,   tc_value: ''
        e   20,   :spell_visual_kit_id,         type: :uint32,  tc_value: ''
      end

      table :creature_movement_info do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :unk_1,                       type: :uint32,  tc_value: ''
      end

      table :creature_type do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :name,                        type: :string,  tc_value: ''
        e   2,    :flags,                       type: :uint32,  tc_value: ''
      end

      table :faction do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :reputation_index,            type: :int32,   tc_value: ''
        e   2,    :reputation_race_mask_1,      type: :uint32,  tc_value: ''
        e   3,    :reputation_race_mask_2,      type: :uint32,  tc_value: ''
        e   4,    :reputation_race_mask_3,      type: :uint32,  tc_value: ''
        e   5,    :reputation_race_mask_4,      type: :uint32,  tc_value: ''
        e   6,    :reputation_class_mask_1,     type: :uint32,  tc_value: ''
        e   7,    :reputation_class_mask_2,     type: :uint32,  tc_value: ''
        e   8,    :reputation_class_mask_3,     type: :uint32,  tc_value: ''
        e   9,    :reputation_class_mask_4,     type: :uint32,  tc_value: ''
        e   10,   :reputation_base_1,           type: :uint32,  tc_value: ''
        e   11,   :reputation_base_2,           type: :uint32,  tc_value: ''
        e   12,   :reputation_base_3,           type: :uint32,  tc_value: ''
        e   13,   :reputation_base_4,           type: :uint32,  tc_value: ''
        e   14,   :reputation_flags_1,          type: :uint32,  tc_value: ''
        e   15,   :reputation_flags_2,          type: :uint32,  tc_value: ''
        e   16,   :reputation_flags_3,          type: :uint32,  tc_value: ''
        e   17,   :reputation_flags_4,          type: :uint32,  tc_value: ''
        e   18,   :parent_faction_id,           type: :uint32,  tc_value: ''
        e   19,   :parent_faction_mod_1,        type: :float,   tc_value: ''
        e   20,   :parent_faction_mod_2,        type: :float,   tc_value: ''
        e   21,   :parent_faction_cap,          type: :uint32,  tc_value: ''
        e   22,   :name,                        type: :string,  tc_value: ''
        e   23,   :description,                 type: :string,  tc_value: ''
        e   24,   :expansion,                   type: :uint32,  tc_value: ''
        e   25,   :flags,                       type: :uint32,  tc_value: ''
        e   26,   :friendship_rep_id,           type: :uint32,  tc_value: ''
      end

      table :gt_npc_total_hp do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :hp,                          type: :float,   tc_value: ''
      end

      table :gt_npc_total_hp_exp1 do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :hp,                          type: :float,   tc_value: ''
      end

      table :gt_npc_total_hp_exp2 do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :hp,                          type: :float,   tc_value: ''
      end

      table :gt_npc_total_hp_exp3 do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :hp,                          type: :float,   tc_value: ''
      end

      table :gt_npc_total_hp_exp4 do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :hp,                          type: :float,   tc_value: ''
      end

      table :gt_npc_total_hp_exp5 do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :hp,                          type: :float,   tc_value: ''
      end

      table :gt_oct_base_hp_by_class do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :ratio,                       type: :float,   tc_value: ''
      end

      table :item do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :item_class,                  type: :uint32,  tc_value: ''
        e   2,    :item_subclass,               type: :uint32,  tc_value: ''
        e   3,    :sound_override_subclass,     type: :int32,   tc_value: ''
        e   4,    :material,                    type: :int32,   tc_value: ''
        e   5,    :inventory_type,              type: :uint32,  tc_value: ''
        e   6,    :sheath,                      type: :uint32,  tc_value: ''
        e   7,    :icon_file_data_id,           type: :uint32,  tc_value: ''
        e   8,    :group_sounds_id,             type: :uint32,  tc_value: ''
      end

      table :item_apperance do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :item_display_id,             type: :uint32,  tc_value: ''
        e   2,    :icon_file_data_id,           type: :uint32,  tc_value: ''
      end

      table :item_sparse do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :item_quality,                type: :uint32,  tc_value: ''
        e   2,    :flags_1,                     type: :uint32,  tc_value: ''
        e   3,    :flags_2,                     type: :uint32,  tc_value: ''
        e   4,    :flags_3,                     type: :uint32,  tc_value: ''
        e   5,    :unk_1,                       type: :float,   tc_value: ''
        e   6,    :unk_2,                       type: :float,   tc_value: ''
        e   7,    :buy_count,                   type: :uint32,  tc_value: ''
        e   8,    :buy_price,                   type: :uint32,  tc_value: ''
        e   9,    :sell_price,                  type: :uint32,  tc_value: ''
        e   10,   :inventory_type,              type: :uint32,  tc_value: ''
        e   11,   :allowable_class,             type: :int32,   tc_value: ''
        e   12,   :allowable_race,              type: :int32,   tc_value: ''
        e   13,   :item_level,                  type: :uint32,  tc_value: ''
        e   14,   :required_level,              type: :int32,   tc_value: ''
        e   15,   :required_skill,              type: :uint32,  tc_value: ''
        e   16,   :required_skill_rank,         type: :uint32,  tc_value: ''
        e   17,   :required_spell,              type: :uint32,  tc_value: ''
        e   18,   :required_honor_rank,         type: :uint32,  tc_value: ''
        e   19,   :required_city_rank,          type: :uint32,  tc_value: ''
        e   20,   :required_reputation_faction, type: :uint32,  tc_value: ''
        e   21,   :required_reputation_rank,    type: :uint32,  tc_value: ''
        e   22,   :max_count,                   type: :uint32,  tc_value: ''
        e   23,   :stackable,                   type: :uint32,  tc_value: ''
        e   24,   :container_slots,             type: :uint32,  tc_value: ''
        e   25,   :item_stat_1_type,            type: :int32,   tc_value: ''
        e   26,   :item_stat_2_type,            type: :int32,   tc_value: ''
        e   27,   :item_stat_3_type,            type: :int32,   tc_value: ''
        e   28,   :item_stat_4_type,            type: :int32,   tc_value: ''
        e   29,   :item_stat_5_type,            type: :int32,   tc_value: ''
        e   30,   :item_stat_6_type,            type: :int32,   tc_value: ''
        e   31,   :item_stat_7_type,            type: :int32,   tc_value: ''
        e   32,   :item_stat_8_type,            type: :int32,   tc_value: ''
        e   33,   :item_stat_9_type,            type: :int32,   tc_value: ''
        e   34,   :item_stat_10_type,           type: :int32,   tc_value: ''
        e   35,   :item_stat_1_value,           type: :int32,   tc_value: ''
        e   36,   :item_stat_2_value,           type: :int32,   tc_value: ''
        e   37,   :item_stat_3_value,           type: :int32,   tc_value: ''
        e   38,   :item_stat_4_value,           type: :int32,   tc_value: ''
        e   39,   :item_stat_5_value,           type: :int32,   tc_value: ''
        e   40,   :item_stat_6_value,           type: :int32,   tc_value: ''
        e   41,   :item_stat_7_value,           type: :int32,   tc_value: ''
        e   42,   :item_stat_8_value,           type: :int32,   tc_value: ''
        e   43,   :item_stat_9_value,           type: :int32,   tc_value: ''
        e   44,   :item_stat_10_value,          type: :int32,   tc_value: ''
        e   45,   :item_stat_1_allocation,      type: :int32,   tc_value: ''
        e   46,   :item_stat_2_allocation,      type: :int32,   tc_value: ''
        e   47,   :item_stat_3_allocation,      type: :int32,   tc_value: ''
        e   48,   :item_stat_4_allocation,      type: :int32,   tc_value: ''
        e   49,   :item_stat_5_allocation,      type: :int32,   tc_value: ''
        e   50,   :item_stat_6_allocation,      type: :int32,   tc_value: ''
        e   51,   :item_stat_7_allocation,      type: :int32,   tc_value: ''
        e   52,   :item_stat_8_allocation,      type: :int32,   tc_value: ''
        e   53,   :item_stat_9_allocation,      type: :int32,   tc_value: ''
        e   54,   :item_stat_10_allocation,     type: :int32,   tc_value: ''
        e   55,   :item_stat_1_socket_cost_multiplier, type: :float, tc_value: ''
        e   56,   :item_stat_2_socket_cost_multiplier, type: :float, tc_value: ''
        e   57,   :item_stat_3_socket_cost_multiplier, type: :float, tc_value: ''
        e   58,   :item_stat_4_socket_cost_multiplier, type: :float, tc_value: ''
        e   59,   :item_stat_5_socket_cost_multiplier, type: :float, tc_value: ''
        e   60,   :item_stat_6_socket_cost_multiplier, type: :float, tc_value: ''
        e   61,   :item_stat_7_socket_cost_multiplier, type: :float, tc_value: ''
        e   62,   :item_stat_8_socket_cost_multiplier, type: :float, tc_value: ''
        e   63,   :item_stat_9_socket_cost_multiplier, type: :float, tc_value: ''
        e   64,   :item_stat_10_socket_cost_multiplier, type: :float, tc_value: ''
        e   65,   :scaling_stat_distribution,   type: :uint32,  tc_value: ''
        e   66,   :damage_type,                 type: :uint32,  tc_value: ''
        e   67,   :delay,                       type: :uint32,  tc_value: ''
        e   68,   :ranged_mod_range,            type: :float,   tc_value: ''
        e   69,   :bonding,                     type: :uint32,  tc_value: ''
        e   70,   :name,                        type: :string,  tc_value: ''
        e   71,   :name_2,                      type: :string,  tc_value: ''
        e   72,   :name_3,                      type: :string,  tc_value: ''
        e   73,   :name_4,                      type: :string,  tc_value: ''
        e   74,   :description,                 type: :string,  tc_value: ''
        e   75,   :page_text,                   type: :uint32,  tc_value: ''
        e   76,   :language_id,                 type: :uint32,  tc_value: ''
        e   77,   :page_material,               type: :uint32,  tc_value: ''
        e   78,   :start_quest,                 type: :uint32,  tc_value: ''
        e   79,   :lock_id,                     type: :uint32,  tc_value: ''
        e   80,   :material,                    type: :int32,   tc_value: ''
        e   81,   :sheath,                      type: :uint32,  tc_value: ''
        e   82,   :random_property,             type: :uint32,  tc_value: ''
        e   83,   :random_suffix,               type: :uint32,  tc_value: ''
        e   84,   :item_set,                    type: :uint32,  tc_value: ''
        e   85,   :area,                        type: :uint32,  tc_value: ''
        e   86,   :map,                         type: :uint32,  tc_value: ''
        e   87,   :bag_family,                  type: :uint32,  tc_value: ''
        e   88,   :totem_category,              type: :uint32,  tc_value: ''
        e   89,   :socket_1_color,              type: :uint32,  tc_value: ''
        e   90,   :socket_2_color,              type: :uint32,  tc_value: ''
        e   91,   :socket_3_color,              type: :uint32,  tc_value: ''
        e   92,   :socket_bonus,                type: :uint32,  tc_value: ''
        e   93,   :gem_properties,              type: :uint32,  tc_value: ''
        e   94,   :armor_damage_modifier,       type: :float,   tc_value: ''
        e   95,   :duration,                    type: :uint32,  tc_value: ''
        e   96,   :item_limit_category,         type: :uint32,  tc_value: ''
        e   97,   :holiday_id,                  type: :uint32,  tc_value: ''
        e   98,   :stat_scaling_factor,         type: :float,   tc_value: ''
        e   99,   :currency_substitution_id,    type: :uint32,  tc_value: ''
        e   100,  :currency_substitution_count, type: :uint32,  tc_value: ''
        e   101,  :item_name_description_id,    type: :uint32,  tc_value: ''
      end

      table :map do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :directory,                   type: :string,  tc_value: ''
        e   2,    :instance_type,               type: :uint32,  tc_value: ''
        e   3,    :flags,                       type: :uint32,  tc_value: ''
        e   4,    :map_type,                    type: :uint32,  tc_value: ''
        e   5,    :unk_1,                       type: :uint32,  tc_value: ''
        e   6,    :map_name,                    type: :string,  tc_value: ''
        e   7,    :area_table_id,               type: :uint32,  tc_value: ''
        e   8,    :map_description_horde,       type: :string,  tc_value: ''
        e   9,    :map_description_alliance,    type: :string,  tc_value: ''
        e   10,   :loading_screen_id,           type: :int32,   tc_value: ''
        e   11,   :minimap_icon_scale,          type: :float,   tc_value: ''
        e   12,   :corpse_map_id,               type: :int32,   tc_value: ''
        e   13,   :corpse_x,                    type: :float,   tc_value: ''
        e   14,   :corpse_y,                    type: :float,   tc_value: ''
        e   15,   :time_of_day_override,        type: :int32,   tc_value: ''
        e   16,   :expansion_id,                type: :uint32,  tc_value: ''
        e   17,   :raid_offset,                 type: :uint32,  tc_value: ''
        e   18,   :max_players,                 type: :uint32,  tc_value: ''
        e   19,   :parent_map_id,               type: :int32,   tc_value: ''
        e   20,   :cosmetic_parent_map_id,      type: :int32,   tc_value: ''
        e   21,   :time_offset,                 type: :uint32,  tc_value: ''
      end

      table :skill_line do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :category_id,                 type: :uint32,  tc_value: ''
        e   2,    :display_name,                type: :string,  tc_value: ''
        e   3,    :description,                 type: :string,  tc_value: ''
        e   4,    :spell_icon_id,               type: :uint32,  tc_value: ''
        e   5,    :alternate_verb,              type: :string,  tc_value: ''
        e   6,    :can_link,                    type: :uint32,  tc_value: ''
        e   7,    :parent_skill_line_id,        type: :uint32,  tc_value: ''
        e   8,    :flags,                       type: :uint32,  tc_value: ''
      end

      table :spell do
        e   0,    :id,                          type: :uint32,  tc_value: 'ID'
        e   1,    :name,                        type: :string,  tc_value: 'Name_lang'
        e   2,    :name_subtext,                type: :string,  tc_value: 'NameSubtext_lang'
        e   3,    :description,                 type: :string,  tc_value: 'Description'
        e   4,    :aura_description,            type: :string,  tc_value: 'AuraDescription_lang'
        e   5,    :rune_cost_id,                type: :uint32,  tc_value: 'RuneCostID'
        e   6,    :spell_missile_id,            type: :uint32,  tc_value: 'SpellMissileID'
        e   7,    :description_variables_id,    type: :uint32,  tc_value: 'DescriptionVariablesID'
        e   8,    :scaling_id,                  type: :uint32,  tc_value: 'ScalingID'
        e   9,    :aura_options_id,             type: :uint32,  tc_value: 'AuraOptionsID'
        e   10,   :aura_restrictions_id,        type: :uint32,  tc_value: 'AuraRestrictionsID'
        e   11,   :casting_requirements_id,     type: :uint32,  tc_value: 'CastingRequirementsID'
        e   12,   :categories_id,               type: :uint32,  tc_value: 'CategoriesID'
        e   13,   :class_options_id,            type: :uint32,  tc_value: 'ClassOptionsID'
        e   14,   :cooldowns_id,                type: :uint32,  tc_value: 'CooldownsID'
        e   15,   :equipped_items_id,           type: :uint32,  tc_value: 'EquippedItemsID'
        e   16,   :interrupts_id,               type: :uint32,  tc_value: 'InterruptsID'
        e   17,   :levels_id,                   type: :uint32,  tc_value: 'LevelsID'
        e   18,   :reagents_id,                 type: :uint32,  tc_value: 'ReagentsID'
        e   19,   :shapeshift_id,               type: :uint32,  tc_value: 'ShapeshiftID'
        e   20,   :target_restrictions_id,      type: :uint32,  tc_value: 'TargetRestrictionsID'
        e   21,   :totems_id,                   type: :uint32,  tc_value: 'TotemsID'
        e   22,   :required_project_id,         type: :uint32,  tc_value: 'RequiredProjectID'
        e   23,   :misc_id,                     type: :uint32,  tc_value: 'MiscID'
      end

      table :spell_icon do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :icon_path,                   type: :string,  tc_value: ''
      end
    end
  end
end
