module WOW::Definitions
  build 19033 do
    namespace :guid_types do
      table :high do
        e   0,    :null,                tc_value: 'Null'
        e   1,    :uniq,                tc_value: 'Uniq'
        e   2,    :player,              tc_value: 'Player'
        e   3,    :item,                tc_value: 'Item'
        e   4,    :static_door,         tc_value: 'StaticDoor'
        e   5,    :transport,           tc_value: 'Transport'
        e   6,    :conversation,        tc_value: 'Conversation'
        e   7,    :creature,            tc_value: 'Creature'
        e   8,    :vehicle,             tc_value: 'Vehicle'
        e   9,    :pet,                 tc_value: 'Pet'
        e   10,   :game_object,         tc_value: 'GameObject'
        e   11,   :dynamic_object,      tc_value: 'DynamicObject'
        e   12,   :area_trigger,        tc_value: 'AreaTrigger'
        e   13,   :corpse,              tc_value: 'Corpse'
        e   14,   :loot_object,         tc_value: 'LootObject'
        e   15,   :scene_object,        tc_value: 'SceneObject'
        e   16,   :scenario,            tc_value: 'Scenario'
        e   17,   :ai_group,            tc_value: 'AIGroup'
        e   18,   :dynamic_door,        tc_value: 'DynamicDoor'
        e   19,   :client_actor,        tc_value: 'ClientActor'
        e   20,   :vignette,            tc_value: 'Vignette'
        e   21,   :call_for_help,       tc_value: 'CallForHelp'
        e   22,   :ai_resource,         tc_value: 'AIResource'
        e   23,   :ai_lock,             tc_value: 'AILock'
        e   24,   :ai_lock_ticket,      tc_value: 'AILockTicket'
        e   25,   :chat_channel,        tc_value: 'ChatChannel'
        e   26,   :party,               tc_value: 'Party'
        e   27,   :guild,               tc_value: 'Guild'
        e   28,   :wow_account,         tc_value: 'WowAccount'
        e   29,   :bnet_account,        tc_value: 'BNetAccount'
        e   30,   :gm_task,             tc_value: 'GMTask'
        e   31,   :mobile_session,      tc_value: 'MobileSession'
        e   32,   :raid_group,          tc_value: 'RaidGroup'
        e   33,   :spell,               tc_value: 'Spell'
        e   34,   :mail,                tc_value: 'Mail'
        e   35,   :web_obj,             tc_value: 'WebObj'
        e   36,   :lfg_object,          tc_value: 'LFGObject'
        e   37,   :lfg_list,            tc_value: 'LFGList'
        e   38,   :user_router,         tc_value: 'UserRouter'
        e   39,   :pvp_queue_group,     tc_value: 'PVPQueueGroup'
        e   40,   :user_client,         tc_value: 'UserClient'
        e   41,   :pet_battle,          tc_value: 'PetBattle'
        e   42,   :unique_user_client,  tc_value: 'UniqueUserClient'
        e   43,   :battle_pet,          tc_value: 'BattlePet'
      end
    end
  end
end
