module WOW::Definitions
  build 8606 do
    table :chat_message_types do
      e   -1,   :addon,                   tc_value: 'Addon'
      e   0,    :system,                  tc_value: 'System'
      e   1,    :say,                     tc_value: 'Say'
      e   2,    :party,                   tc_value: 'Party'
      e   3,    :raid,                    tc_value: 'Raid'
      e   4,    :guild,                   tc_value: 'Guild'
      e   5,    :officer,                 tc_value: 'Officer'
      e   6,    :yell,                    tc_value: 'Yell'
      e   7,    :whisper,                 tc_value: 'Whisper'
      e   8,    :whisper_foreign,         tc_value: 'WhisperForeign'
      e   9,    :whisper_inform,          tc_value: 'WhisperInform'
      e   10,   :emote,                   tc_value: 'Emote'
      e   11,   :text_emote,              tc_value: 'TextEmote'
      e   12,   :monster_say,             tc_value: 'MonsterSay'
      e   13,   :monster_party,           tc_value: 'MonsterParty'
      e   14,   :monster_yell,            tc_value: 'MonsterYell'
      e   15,   :monster_whisper,         tc_value: 'MonsterWhisper'
      e   16,   :monster_emote,           tc_value: 'MonsterEmote'
      e   17,   :channel,                 tc_value: 'Channel'
      e   18,   :channel_join,            tc_value: 'ChannelJoin'
      e   19,   :channel_leave,           tc_value: 'ChannelLeave'
      e   20,   :channel_list,            tc_value: 'ChannelList'
      e   21,   :channel_notice,          tc_value: 'ChannelNotice'
      e   22,   :channel_notice_user,     tc_value: 'ChannelNoticeUser'
      e   23,   :afk,                     tc_value: 'Afk'
      e   24,   :dnd,                     tc_value: 'Dnd'
      e   25,   :ignored,                 tc_value: 'Ignored'
      e   26,   :skill,                   tc_value: 'Skill'
      e   27,   :loot,                    tc_value: 'Loot'
      e   28,   :money,                   tc_value: 'Money'
      e   29,   :opening,                 tc_value: 'Opening'
      e   30,   :tradeskills,             tc_value: 'Tradeskills'
      e   31,   :pet_info,                tc_value: 'PetInfo'
      e   32,   :combat_misc_info,        tc_value: 'CombatMiscInfo'
      e   33,   :combat_xp_gain,          tc_value: 'CombatXPGain'
      e   34,   :combat_honor_gain,       tc_value: 'CombatHonorGain'
      e   35,   :combat_faction_change,   tc_value: 'CombatFactionChange'
      e   36,   :battleground_neutral,    tc_value: 'BattlegroundNeutral'
      e   37,   :battleground_alliance,   tc_value: 'BattlegroundAlliance'
      e   38,   :battleground_horde,      tc_value: 'BattlegroundHorde'
      e   39,   :raid_leader,             tc_value: 'RaidLeader'
      e   40,   :raid_warning,            tc_value: 'RaidWarning'
      e   41,   :raid_boss_emote,         tc_value: 'RaidBossEmote'
      e   42,   :raid_boss_whisper,       tc_value: 'RaidBossWhisper'
      e   43,   :filtered,                tc_value: 'Filtered'
      e   44,   :battleground,            tc_value: 'Battleground'
      e   45,   :battleground_leader,     tc_value: 'BattlegroundLeader'
      e   46,   :restricted,              tc_value: 'Restricted'
      e   47,   :battlenet,               tc_value: 'BattleNet'
      e   48,   :achievement,             tc_value: 'Achievement'
      e   49,   :guild_achievement,       tc_value: 'GuildAchievement'
      e   50,   :arena_points,            tc_value: 'ArenaPoints'
      e   51,   :party_leader,            tc_value: 'PartyLeader'
    end
  end
end
