module WOW
  module DB; end
end

require_relative 'db/records'
require_relative 'db/records/base'

require_relative 'db/records/achievement'
require_relative 'db/records/area_table'
require_relative 'db/records/char_titles'
require_relative 'db/records/creature_family'
require_relative 'db/records/item'
require_relative 'db/records/item_appearance'
require_relative 'db/records/item_sparse'
require_relative 'db/records/creature'
require_relative 'db/records/creature_difficulty'
require_relative 'db/records/creature_display_info'
require_relative 'db/records/creature_movement_info'
require_relative 'db/records/creature_type'
require_relative 'db/records/faction'
require_relative 'db/records/file_data'
require_relative 'db/records/gt_npc_total_hp'
require_relative 'db/records/gt_npc_total_hp_exp1'
require_relative 'db/records/gt_npc_total_hp_exp2'
require_relative 'db/records/gt_npc_total_hp_exp3'
require_relative 'db/records/gt_npc_total_hp_exp4'
require_relative 'db/records/gt_npc_total_hp_exp5'
require_relative 'db/records/gt_oct_base_hp_by_class'
require_relative 'db/records/item_display_info'
require_relative 'db/records/map'
require_relative 'db/records/skill_line'
require_relative 'db/records/spell'
require_relative 'db/records/spell_icon'
