module WOW::Definitions
  build 20182 do
    namespace :db2 do
      table :creature do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :creature_type_id,            type: :uint32,  tc_value: ''
        e   2,    :unk_1,                       type: :uint32,  tc_value: ''
        e   3,    :unk_2,                       type: :uint32,  tc_value: ''
        e   4,    :unk_3,                       type: :uint32,  tc_value: ''
        e   5,    :unk_4,                       type: :uint32,  tc_value: ''
        e   6,    :unk_5,                       type: :uint32,  tc_value: ''
        e   7,    :unk_6,                       type: :uint32,  tc_value: ''
        e   8,    :unk_7,                       type: :uint32,  tc_value: ''
        e   9,    :unk_8,                       type: :uint32,  tc_value: ''
        e   10,   :unk_9,                       type: :uint32,  tc_value: ''
        e   11,   :unk_10,                      type: :uint32,  tc_value: ''
        e   12,   :unk_11,                      type: :uint32,  tc_value: ''
        e   13,   :unk_12,                      type: :uint32,  tc_value: ''
        e   14,   :name,                        type: :string,  tc_value: ''
        e   15,   :unk_13,                      type: :uint32,  tc_value: ''
        e   16,   :unk_14,                      type: :uint32,  tc_value: ''
        e   17,   :unk_15,                      type: :uint32,  tc_value: ''
        e   18,   :unk_16,                      type: :uint32,  tc_value: ''
        e   19,   :unk_17,                      type: :uint32,  tc_value: ''
      end

      table :creature_difficulty do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :creature_id,                 type: :uint32,  tc_value: ''
        e   2,    :faction_id,                  type: :uint32,  tc_value: ''
        e   3,    :expansion,                   type: :uint32,  tc_value: ''
        e   4,    :minimum_level,               type: :uint32,  tc_value: ''
        e   5,    :maximum_level,               type: :uint32,  tc_value: ''
        e   6,    :flags_1,                     type: :uint32,  tc_value: ''
        e   7,    :flags_2,                     type: :uint32,  tc_value: ''
        e   8,    :flags_3,                     type: :uint32,  tc_value: ''
        e   9,    :flags_4,                     type: :uint32,  tc_value: ''
        e   10,   :flags_5,                     type: :uint32,  tc_value: ''
      end

      table :creature_display_info do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :creature_model_id,           type: :uint32,  tc_value: ''
        e   2,    :creature_sound_id,           type: :uint32,  tc_value: ''
        e   3,    :creature_display_extra_id,   type: :uint32,  tc_value: ''
        e   4,    :creature_model_scale,        type: :float,   tc_value: ''
        e   5,    :unk_1,                       type: :float,   tc_value: ''
        e   6,    :creature_model_alpha,        type: :uint32,  tc_value: ''
        e   7,    :texture_variation_1_name,    type: :string,  tc_value: ''
        e   8,    :texture_variation_2_name,    type: :string,  tc_value: ''
        e   9,    :texture_variation_3_name,    type: :string,  tc_value: ''
        e   10,   :portrait_texture_name,       type: :string,  tc_value: ''
        e   11,   :size_class,                  type: :uint32,  tc_value: ''
        e   12,   :blood,                       type: :int32,   tc_value: ''
        e   13,   :npc_sound_id,                type: :uint32,  tc_value: ''
        e   14,   :particle_color_id,           type: :uint32,  tc_value: ''
        e   15,   :creature_geoset_data,        type: :uint32,  tc_value: ''
        e   16,   :object_effect_package_id,    type: :uint32,  tc_value: ''
        e   17,   :anim_replacement_set_id,     type: :uint32,  tc_value: ''
        e   18,   :flags,                       type: :uint32,  tc_value: ''
        e   19,   :gender,                      type: :int32,   tc_value: ''
        e   20,   :spell_visual_kit_id,         type: :uint32,  tc_value: ''
      end

      table :creature_movement_info do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :unk_1,                       type: :uint32,  tc_value: ''
      end

      table :creature_type do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :name,                        type: :string,  tc_value: ''
        e   2,    :flags,                       type: :uint32,  tc_value: ''
      end

      table :item do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :item_class,                  type: :uint32,  tc_value: ''
        e   2,    :item_subclass,               type: :uint32,  tc_value: ''
        e   3,    :sound_override_subclass,     type: :int32,   tc_value: ''
        e   4,    :material,                    type: :int32,   tc_value: ''
        e   5,    :inventory_type,              type: :uint32,  tc_value: ''
        e   6,    :sheath,                      type: :uint32,  tc_value: ''
        e   7,    :icon_file_data_id,           type: :uint32,  tc_value: ''
        e   8,    :group_sounds_id,             type: :uint32,  tc_value: ''
      end

      table :item_apperance do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :item_display_id,             type: :uint32,  tc_value: ''
        e   2,    :icon_file_data_id,           type: :uint32,  tc_value: ''
      end

      table :item_sparse do
        e   0,    :id,                          type: :uint32,  tc_value: ''
        e   1,    :item_quality,                type: :uint32,  tc_value: ''
        e   2,    :flags_1,                     type: :uint32,  tc_value: ''
        e   3,    :flags_2,                     type: :uint32,  tc_value: ''
        e   4,    :flags_3,                     type: :uint32,  tc_value: ''
        e   5,    :unk_1,                       type: :float,   tc_value: ''
        e   6,    :unk_2,                       type: :float,   tc_value: ''
        e   7,    :buy_count,                   type: :uint32,  tc_value: ''
        e   8,    :buy_price,                   type: :uint32,  tc_value: ''
        e   9,    :sell_price,                  type: :uint32,  tc_value: ''
        e   10,   :inventory_type,              type: :uint32,  tc_value: ''
        e   11,   :allowable_class,             type: :int32,   tc_value: ''
        e   12,   :allowable_race,              type: :int32,   tc_value: ''
        e   13,   :item_level,                  type: :uint32,  tc_value: ''
        e   14,   :required_level,              type: :int32,   tc_value: ''
        e   15,   :required_skill,              type: :uint32,  tc_value: ''
        e   16,   :required_skill_rank,         type: :uint32,  tc_value: ''
        e   17,   :required_spell,              type: :uint32,  tc_value: ''
        e   18,   :required_honor_rank,         type: :uint32,  tc_value: ''
        e   19,   :required_city_rank,          type: :uint32,  tc_value: ''
        e   20,   :required_reputation_faction, type: :uint32,  tc_value: ''
        e   21,   :required_reputation_rank,    type: :uint32,  tc_value: ''
        e   22,   :max_count,                   type: :uint32,  tc_value: ''
        e   23,   :stackable,                   type: :uint32,  tc_value: ''
        e   24,   :container_slots,             type: :uint32,  tc_value: ''
        e   25,   :item_stat_1_type,            type: :int32,   tc_value: ''
        e   26,   :item_stat_2_type,            type: :int32,   tc_value: ''
        e   27,   :item_stat_3_type,            type: :int32,   tc_value: ''
        e   28,   :item_stat_4_type,            type: :int32,   tc_value: ''
        e   29,   :item_stat_5_type,            type: :int32,   tc_value: ''
        e   30,   :item_stat_6_type,            type: :int32,   tc_value: ''
        e   31,   :item_stat_7_type,            type: :int32,   tc_value: ''
        e   32,   :item_stat_8_type,            type: :int32,   tc_value: ''
        e   33,   :item_stat_9_type,            type: :int32,   tc_value: ''
        e   34,   :item_stat_10_type,           type: :int32,   tc_value: ''
        e   35,   :item_stat_1_value,           type: :int32,   tc_value: ''
        e   36,   :item_stat_2_value,           type: :int32,   tc_value: ''
        e   37,   :item_stat_3_value,           type: :int32,   tc_value: ''
        e   38,   :item_stat_4_value,           type: :int32,   tc_value: ''
        e   39,   :item_stat_5_value,           type: :int32,   tc_value: ''
        e   40,   :item_stat_6_value,           type: :int32,   tc_value: ''
        e   41,   :item_stat_7_value,           type: :int32,   tc_value: ''
        e   42,   :item_stat_8_value,           type: :int32,   tc_value: ''
        e   43,   :item_stat_9_value,           type: :int32,   tc_value: ''
        e   44,   :item_stat_10_value,          type: :int32,   tc_value: ''
        e   45,   :item_stat_1_allocation,      type: :int32,   tc_value: ''
        e   46,   :item_stat_2_allocation,      type: :int32,   tc_value: ''
        e   47,   :item_stat_3_allocation,      type: :int32,   tc_value: ''
        e   48,   :item_stat_4_allocation,      type: :int32,   tc_value: ''
        e   49,   :item_stat_5_allocation,      type: :int32,   tc_value: ''
        e   50,   :item_stat_6_allocation,      type: :int32,   tc_value: ''
        e   51,   :item_stat_7_allocation,      type: :int32,   tc_value: ''
        e   52,   :item_stat_8_allocation,      type: :int32,   tc_value: ''
        e   53,   :item_stat_9_allocation,      type: :int32,   tc_value: ''
        e   54,   :item_stat_10_allocation,     type: :int32,   tc_value: ''
        e   55,   :item_stat_1_socket_cost_multiplier, type: :float, tc_value: ''
        e   56,   :item_stat_2_socket_cost_multiplier, type: :float, tc_value: ''
        e   57,   :item_stat_3_socket_cost_multiplier, type: :float, tc_value: ''
        e   58,   :item_stat_4_socket_cost_multiplier, type: :float, tc_value: ''
        e   59,   :item_stat_5_socket_cost_multiplier, type: :float, tc_value: ''
        e   60,   :item_stat_6_socket_cost_multiplier, type: :float, tc_value: ''
        e   61,   :item_stat_7_socket_cost_multiplier, type: :float, tc_value: ''
        e   62,   :item_stat_8_socket_cost_multiplier, type: :float, tc_value: ''
        e   63,   :item_stat_9_socket_cost_multiplier, type: :float, tc_value: ''
        e   64,   :item_stat_10_socket_cost_multiplier, type: :float, tc_value: ''
        e   65,   :scaling_stat_distribution,   type: :uint32,  tc_value: ''
        e   66,   :damage_type,                 type: :uint32,  tc_value: ''
        e   67,   :delay,                       type: :uint32,  tc_value: ''
        e   68,   :ranged_mod_range,            type: :float,   tc_value: ''
        e   69,   :bonding,                     type: :uint32,  tc_value: ''
        e   70,   :name,                        type: :string,  tc_value: ''
        e   71,   :name_2,                      type: :string,  tc_value: ''
        e   72,   :name_3,                      type: :string,  tc_value: ''
        e   73,   :name_4,                      type: :string,  tc_value: ''
        e   74,   :description,                 type: :string,  tc_value: ''
        e   75,   :page_text,                   type: :uint32,  tc_value: ''
        e   76,   :language_id,                 type: :uint32,  tc_value: ''
        e   77,   :page_material,               type: :uint32,  tc_value: ''
        e   78,   :start_quest,                 type: :uint32,  tc_value: ''
        e   79,   :lock_id,                     type: :uint32,  tc_value: ''
        e   80,   :material,                    type: :int32,   tc_value: ''
        e   81,   :sheath,                      type: :uint32,  tc_value: ''
        e   82,   :random_property,             type: :uint32,  tc_value: ''
        e   83,   :random_suffix,               type: :uint32,  tc_value: ''
        e   84,   :item_set,                    type: :uint32,  tc_value: ''
        e   85,   :area,                        type: :uint32,  tc_value: ''
        e   86,   :map,                         type: :uint32,  tc_value: ''
        e   87,   :bag_family,                  type: :uint32,  tc_value: ''
        e   88,   :totem_category,              type: :uint32,  tc_value: ''
        e   89,   :socket_1_color,              type: :uint32,  tc_value: ''
        e   90,   :socket_2_color,              type: :uint32,  tc_value: ''
        e   91,   :socket_3_color,              type: :uint32,  tc_value: ''
        e   92,   :socket_bonus,                type: :uint32,  tc_value: ''
        e   93,   :gem_properties,              type: :uint32,  tc_value: ''
        e   94,   :armor_damage_modifier,       type: :float,   tc_value: ''
        e   95,   :duration,                    type: :uint32,  tc_value: ''
        e   96,   :item_limit_category,         type: :uint32,  tc_value: ''
        e   97,   :holiday_id,                  type: :uint32,  tc_value: ''
        e   98,   :stat_scaling_factor,         type: :float,   tc_value: ''
        e   99,   :currency_substitution_id,    type: :uint32,  tc_value: ''
        e   100,  :currency_substitution_count, type: :uint32,  tc_value: ''
        e   101,  :item_name_description_id,    type: :uint32,  tc_value: ''
      end
    end
  end
end
